[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
remappings = [
    "forge-std=lib/forge-std/src/",
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@era-contracts=lib/foundry-era-contracts/src/system-contracts/contracts/",
]
optimizer = true
via_ir = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.zksync]
src = "src/zksync"
out = "out"
libs = ["lib"]
test = "test/zksync"
script = "script/zksync"
remappings = [
    "forge-std=lib/forge-std/src/",
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@era-contracts=lib/foundry-era-contracts/src/system-contracts/contracts/",
]
optimizer = true
via_ir = true
fs_permissions = [{ access = "read", path = "./zkout" }]
